[SETTINGS]
#1 Red (紅色)	中心線、剖面線、重要的錯誤標記、禁止區。
#2 Yellow (黃色)	文字 (Text)、尺寸線 (Dimension Lines)、零件名稱。
#3 Green (綠色)	輪廓線、剖視圖邊界、完成面。
#4 Cyan (青色)	球標 (Balloon)、公差標註、參考線。
#5 Blue (藍色)	虛線、隱藏線 (Hidden Lines)、水塔或水路標示。
#6 Magenta (洋紅色)	圖框、標題欄邊界、特殊的工藝說明文字。
#7 White/Black	基礎結構線、主要零件輪廓 (黑白隨背景切換)。
COLOR = 4

# 成對球標距離門檻
DIST_RANGE_MIN = 16
DIST_RANGE_MAX = 21

# 圖紙最大邊界 (X, Y)
LIMMAX_X = 1600
LIMMAX_Y = 1108

# 圖紙分區數量 (X-16區, Y-8區)
SEGMENT_X = 16
SEGMENT_Y = 8

# 些微旋轉的成對球標仍會成對
ANGLE_TOL = 0.5

# 成對球標的水平位移容許值
DIST_OFFSET = 2
