[FILTER]
# 青色為球標色
COLOR = 4

# 範圍球標搜尋距離，旋轉角度容許誤差
MIN_DIST = 17.5
MAX_DIST = 20.5
TOLERANCE_ROT = 2.0  

# 水平(垂直)時，Y軸(X軸)的位移容許誤差內，才能配對成範圍球標
ORTHO_TOL = 1.0


# 搜尋公差文時規則: 
# (1) 水平(垂直)右側(上側) 的矩形空間優先 : MAX_RIGHT_SIDE_DIST + MAX_BOTTOM_SIDE_DIST   
# (2) 全方位搜尋不超過 MAX_MATCH_DIST
MAX_RIGHT_SIDE_DIST = 50.0
MAX_BOTTOM_SIDE_DIST = 10.0   
MAX_MATCH_DIST = 50.0


# 搜尋PPK位子範圍
MAX_PPK_DIST = 20.0
